[package]
name = "exchange_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.3", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = "0.3"
